language: swift
osx_image: xcode11.4
xcode_workspace: Fowl\ Weather.xcworkspace
xcode_scheme: Fowl\ Weather
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone X
before_install:
    - cd Fowl\ Weather
    - pod install
